from os.path import dirname, abspath
import sys

sys.path.insert(0, dirname(dirname(dirname(abspath(__file__)))))
from utils import performTests, getAnswer  # noqa E402

def parseInformation(filename):
    file = open(filename, "r")
    s = file.read()
    rows = s.split('\n')
    secrets= []
    for row in rows:
        secrets.append(int(row))
    return secrets

def secretGeneration(secrets):
    sequences = {}
    for secret in secrets:
        tmpSecret = secret
        diff = []
        for i in range(2000):
            prevSecret = tmpSecret
            tmpSecret = (tmpSecret*64) ^ tmpSecret
            tmpSecret = tmpSecret%16777216

            tmpSecret = (tmpSecret//32) ^ tmpSecret
            tmpSecret = tmpSecret%16777216

            tmpSecret = (tmpSecret*2048) ^ tmpSecret
            tmpSecret = tmpSecret%16777216
            diff.append(tmpSecret%10-prevSecret%10)
            if len(diff)>3:
                seq =(diff[-4], diff[-3], diff[-2], diff[-1]) 
                if seq in sequences:
                    if secret in sequences[seq]:
                        continue
                    else:
                        sequences[seq][secret]=tmpSecret%10
                else:
                    sequences[seq]={secret:tmpSecret%10}
    maxi = -float('inf')
    for seq in sequences:
        net = 0
        for val in sequences[seq]:
            net+= sequences[seq][val]
        if net>maxi:
            maxi = net
    return maxi

def main(filename):
    secrets = parseInformation(filename)
    net= secretGeneration(secrets)
    return net

if __name__ == "__main__":
    args = sys.argv[1:]
    if args[0] == "test":
        test = True
    elif args[0] == "main":
        test = False
    else:
        raise Exception('Wrong argument, expected "test" or "main"')
    if test:
        performTests(2024, 22, [23],main, test=['2']) 
    else:
        s = getAnswer(2024, 22, main)
        print("The sum of of the 2000th number generated by each buyer is {0}".format(s))