from os.path import dirname, abspath
import sys
import time

sys.path.insert(0, dirname(dirname(dirname(abspath(__file__)))))
from utils import performTests, getAnswer  # noqa E402

def parseInformation(filename):
    file = open(filename, "r")
    s = file.read()
    rows = s.split('\n')
    graph = {}
    for row in rows:
        tmp = row.split('-')
        for idx,node in enumerate(tmp):
            if node in graph:
                graph[node].add(tmp[abs(idx-1)])
            else:
                graph[node] = {tmp[abs(idx-1)]}
    return graph

def checkNetwork(graph):
    curSets = set() 
    for node1 in graph:
        for node2 in graph[node1]:
            for node3 in graph[node2]:
                if node1 in graph[node3]:
                    tmp = tuple(sorted([node1,node2,node3]))
                    if  tmp not in curSets:
                        curSets.add(tmp)
    steps = 13 
    for _ in range(steps-3):
        newSets = set() 
        for s in curSets:
            tmpS = set(s)
            graphSubset = graph[tmpS.pop()] 
            while tmpS:
                graphSubset = graphSubset.intersection(graph[tmpS.pop()])
            tmpS = set(s)
            for newNode in graphSubset:
                if newNode not in tmpS:
                    addNode = True
                    for node in s:
                        if node in graph[newNode]:
                            continue
                        else:
                            addNode = False
                            break
                    if addNode:
                        tmpS.add(newNode)
                        tmp = tuple(sorted(tmpS))
                        newSets.add(tmp)
        curSets = newSets
    out = curSets.pop()
    return ','.join(out)


def main(filename):
    graph = parseInformation(filename)
    triads= checkNetwork(graph)
    return triads

if __name__ == "__main__":
    args = sys.argv[1:]
    if args[0] == "test":
        test = True
    elif args[0] == "main":
        test = False
    else:
        raise Exception('Wrong argument, expected "test" or "main"')
    if test:
        performTests(2024, 23, ['co,de,ka,ta'],main) 
    else:
        n = getAnswer(2024, 23, main)
        print("The password generated by the biggest interconnected network is {0}".format(n))